#!/usr/bin/env bash
# Configures Nginx server to redirect to another page.

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

new_string="server_name _;\n\trewrite ^\/redirect_me http:\/\/pixelspark.tech permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

service nginx restart
