#!/usr/bin/env bash
# Creates a custom 404 page

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configures Nginx server to redirect to another page.
new_string="server_name _;\n\trewrite ^\/redirect_me http:\/\/pixelspark.tech permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

error_block="\
    error_page 404 /404.html;\n\
    location = /404.html {\n\
        internal;\n\
    }"

sed -i "/server {/a $error_block" /etc/nginx/sites-available/default

service nginx restart
