#!/usr/bin/env bash
# Creates a custom 404 page

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configures Nginx server to redirect to another page.
new_string="server_name _;\n\trewrite ^\/redirect_me http:\/\/pixelspark.tech permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

error_block="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$error_block/" /etc/nginx/sites-enabled/default

service nginx restart
