#!/usr/bin/env bash
# Install and configure HAproxy
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get install -y haproxy=2.0.\*

echo "
frontend http_front
        bind *:80
        default_backend http_back

backend http_back
        balance roundrobin
        mode http
        server 500720-web-01 100.25.211.5:80 check
        server 500720-web-02 54.90.20.242:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" > /etc/default/haproxy

service haproxy start
