#!/usr/bin/env bash
# Manages manage_my_process

PID_FILE="/var/run/my_process.pid"

if [ "$1" = "start" ]
then
    ./manage_my_process &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
elif [ "$1" = "stop" ]
then
    pid=$(cat "$PID_FILE")
    if ps -p "$pid" > /dev/null
    then
        kill "$pid"
    fi
    rm "$PID_FILE"
    echo "manage_my_process stopped"
elif [ "$1" = "restart" ]
then
    pid=$(cat "$PID_FILE")
    if ps -p "$pid" > /dev/null
    then
        kill "$pid"
    fi
    rm "$PID_FILE"
    ./manage_my_process &
    echo $! > "$PID_FILE"
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
