#!/usr/bin/env bash
# Makes up a story about /etc/passwd

file="/etc/passwd"

exec 3< "$file"

while IFS=":" read -r username password userid groupid useridinfo homedir shell <&3
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done

exec 3<&-
