#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
#+ where hours are displayed from 0 to 12
#+ and minutes are displayed from 1 to 59

h=0
m=1

while [ $h -le 12 ]
do
    echo "Hour: $h"

    while [ $m -le 59 ]
    do
        echo "$m"

        (( m++ ))
    done

    m=1

    (( h++ ))
done
