#!/usr/bin/env bash
# Make nginx run as nginx user
sed -i 's/#?user .*/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
su -c service nginx start nginx
